# Â© 2025 Thor Thor
# Contact: codethor@gmail.com
# LinkedIn: https://www.linkedin.com/in/thor-thor0
# SPDX-License-Identifier: MIT

[workspace]
members = [
    "crypto",
    "p2p",
    "node",
    "cli",
]

[patch.crates-io]
if-watch = { path = "third_party/if-watch" }