[package]
name = "p2p"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
libp2p = { version = "0.54", features = ["quic", "mdns", "tokio", "macros"] }
cryprq-crypto = { path = "../crypto" }
zeroize = "1.8"
once_cell = "1.21"
