[package]
name = "crypto"
version = "0.1.0"
edition = "2024"

[dependencies]

[dependencies]
rosenpass = { git = "https://github.com/rosenpass/rosenpass", branch = "main", default-features = false }
rand_core = { version = "0.6", default-features = false }
